export const ProductConfig = [
  {
    id: 1,
    name: "garam_masala",
    path: "/products/garam-masala",
    src: "/images/products/garam-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 2,
    name: "tandoori_masala",
    path: "/products/tandoori-masala",
    src: "/images/products/tandoori-masala.jpg",
    originalPrice: 54.0,
    discountedPrice: 50.0,
  },
  {
    id: 3,
    name: "Chaat Masala",
    path: "/products/chaat-masala",
    src: "/images/products/chaat-masala.jpg",
    originalPrice: 14.0,
    discountedPrice: 12.0,
  },
  {
    id: 4,
    name: "Kitchen King Masala",
    path: "/products/kitchen-king-masala",
    src: "/images/products/kitchen-king-masala.webp",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 5,
    name: "Pav Bhaji Masala",
    path: "/products/pav-bhaji-masala",
    src: "/images/products/pav-bhaji-masala.webp",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 6,
    name: "Biryani Masala",
    path: "/products/biryani-masala",
    src: "/images/products/biryani-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 7,
    name: "Sambar Masala",
    path: "/products/sambar-masala",
    src: "/images/products/sambar-masala.webp",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 8,
    name: "Rajma Masala",
    path: "/products/rajma-masala",
    src: "/images/products/rajma-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 9,
    name: "Chana Masala",
    path: "/products/chana-masala",
    src: "/images/products/chana-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 10,
    name: "Curry Masala",
    path: "/products/curry-masala",
    src: "/images/products/curry-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 11,
    name: "Chana Masala",
    path: "/products/chana-masala",
    src: "/images/products/chana-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 12,
    name: "Curry Masala",
    path: "/products/curry-masala",
    src: "/images/products/curry-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 3,
    name: "Chana Masala",
    path: "/products/chana-masala",
    src: "/images/products/chana-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 14,
    name: "Curry Masala",
    path: "/products/curry-masala",
    src: "/images/products/curry-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 15,
    name: "Chana Masala",
    path: "/products/chana-masala",
    src: "/images/products/chana-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
  {
    id: 16,
    name: "Curry Masala",
    path: "/products/curry-masala",
    src: "/images/products/curry-masala.jpg",
    originalPrice: 24.0,
    discountedPrice: 18.0,
  },
];
