import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { LanguageProvider } from "@/context/LanguageContext";
import DynamicLayout from "@/layout/DynamicLayout";

// import { styled } from "@mui/material/styles";
// import Button from "@mui/material/Button";

// const CustomButton = styled(Button)`
//   background-color: #1976d2;
//   color: white;
//   &:hover {
//     background-color: #1565c0;
//   }
// `;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LanguageProvider>
          <DynamicLayout>{children}</DynamicLayout>
        </LanguageProvider>
      </body>
    </html>
  );
}
